name: calculator_module1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Updated to match the latest Flutter version

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.4.0  # Updated to a version compatible with firebase_core ^2.27.2
  cupertino_icons: ^1.0.6
  math_expressions: ^2.4.0
  firebase_core: ^2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

